### PR TITLE
stop reporting failures as successful updates

### LINKED ISSUE #20: Updater always set the latest successful date
Because Update does not return any status, the latest successful update date is always updated even if it failed.

Also, we want to make sure that we don't update the flag of a failed fetcher. Today, fetchers only returns a flag if they succeeded but eventually contributors may start writing fetchers and don't respect that.

### PR DESCRIPTION
**Pull request by jzelinskie**
Fixes #20.

### CODE REVIEW

File: updater/updater.go [hunk 1]
```diff
@@ -93,23 +93,16 @@ func Run(interval time.Duration, st *utils.Stopper) {
...
 						database.Lock(flagName, lockDuration, whoAmI)
 					}
 				}
 
-				// Write the last update time to the database and set the next update
-				// time.
-				now := time.Now().UTC()
-				database.UpdateFlag(flagName, strconv.FormatInt(now.Unix(), 10))
-				healthLatestSuccessfulUpdate = now
-				nextUpdate = now.Add(interval)
```
Comment (Quentin-M) [inline updater/updater.go:111]: If we remove that line, an updater that failed will just wait some random seconds and retry. I guess that's ok?

Comment (jzelinskie) [inline updater/updater.go:111]: Yep

**Comment by Quentin-M** [comment]
LGTM
